[package]
name = "substrate-lite-js"
version = "0.1.3"
authors = ["Parity Technologies <admin@parity.io>", "Pierre Krieger <pierre.krieger1708@gmail.com>"]
description = "Browser bindings to a light client for Substrate-based blockchains"
repository = "https://github.com/paritytech/substrate-lite"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = "0.1.6"
derive_more = "0.99.11"
futures = "0.3.8"
futures-timer = { version = "3.0.2", features = ["wasm-bindgen"] }
js-sys = "0.3.45"
rand = { version = "0.7.0", features = ["wasm-bindgen"] } # TODO: can we remove this `rand` dependency?
substrate-lite = { version = "0.1.0", path = "../..", default-features = false, features = ["wasm-bindings"] }
wasm-bindgen = "0.2.68"
wasm-bindgen-futures = "0.4.18"
web-sys = { version = "0.3.45", features = ["console"] }
wee_alloc = "0.4.5"
