version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    labels: []
    schedule:
      interval: "daily"
    rebase-strategy: disabled  # Redundant with mergify
    open-pull-requests-limit: 2

  - package-ecosystem: "npm"
    directory: "/bin/wasm-node/javascript"
    labels: []
    schedule:
      interval: "daily"
    rebase-strategy: disabled  # Redundant with mergify
    open-pull-requests-limit: 2

  - package-ecosystem: github-actions
    directory: "/"
    labels: []
    schedule:
      interval: "daily"
    rebase-strategy: disabled  # Redundant with mergify
    open-pull-requests-limit: 2
