[package]
name = "substrate-lite-js"
version = "0.1.3"
authors = ["Parity Technologies <admin@parity.io>", "Pierre Krieger <pierre.krieger1708@gmail.com>"]
description = "Browser bindings to a light client for Substrate-based blockchains"
repository = "https://github.com/paritytech/substrate-lite"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
derive_more = "0.99.11"
futures = "0.3.8"
lazy_static = "1.4.0"
lru = "0.6.3"
rand = "0.8.1"
serde_json = "1.0.61"
slab = "0.4.2"
substrate-lite = { version = "0.1.0", path = "../../..", default-features = false }
