[package]
name = "smoldot-js"
version = "0.1.3"
authors = ["Parity Technologies <admin@parity.io>", "Pierre Krieger <pierre.krieger1708@gmail.com>"]
description = "Browser bindings to a light client for Substrate-based blockchains"
repository = "https://github.com/paritytech/smoldot"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
blake2-rfc = { version = "0.2.18", default-features = false }
derive_more = "0.99.11"
futures = "0.3.12"
lazy_static = "1.4.0"
log = "0.4.14"
lru = "0.6.3"
rand = "0.8.3"
serde_json = "1.0.61"
simple_logger = { version = "1.11.0", default-features = false }
slab = "0.4.2"
smoldot = { version = "0.1.0", path = "../../..", default-features = false }
